// Mocks generated by Mockito 5.4.6 from annotations
// in agent_relais/test/features/transfert/data/repositories/transfert_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:agent_relais/core/network/dio_client.dart' as _i2;
import 'package:agent_relais/core/network/network_info.dart' as _i9;
import 'package:agent_relais/core/utils/ussd_transport.dart' as _i10;
import 'package:agent_relais/features/transfert/data/datasources/local/transfert_local_datasource.dart'
    as _i3;
import 'package:agent_relais/features/transfert/data/datasources/remote/transfert_remote_datasource.dart'
    as _i6;
import 'package:agent_relais/features/transfert/data/models/transfert_model.dart'
    as _i5;
import 'package:dio/dio.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDioClient_0 extends _i1.SmartFake implements _i2.DioClient {
  _FakeDioClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TransfertLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransfertLocalDataSource extends _i1.Mock
    implements _i3.TransfertLocalDataSource {
  MockTransfertLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> insertTransfert(_i5.TransfertModel? transfert) =>
      (super.noSuchMethod(
            Invocation.method(#insertTransfert, [transfert]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateStatus(String? submissionId, String? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateStatus, [submissionId, status]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePartsInfo(
    String? submissionId,
    int? totalParts,
    int? partsSent,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePartsInfo, [
              submissionId,
              totalParts,
              partsSent,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.TransfertModel>> getAllTransferts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTransferts, []),
            returnValue: _i4.Future<List<_i5.TransfertModel>>.value(
              <_i5.TransfertModel>[],
            ),
          )
          as _i4.Future<List<_i5.TransfertModel>>);

  @override
  _i4.Future<List<_i5.TransfertModel>> getPendingTransferts() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingTransferts, []),
            returnValue: _i4.Future<List<_i5.TransfertModel>>.value(
              <_i5.TransfertModel>[],
            ),
          )
          as _i4.Future<List<_i5.TransfertModel>>);
}

/// A class which mocks [TransfertRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransfertRemoteDataSource extends _i1.Mock
    implements _i6.TransfertRemoteDataSource {
  MockTransfertRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DioClient get dioClient =>
      (super.noSuchMethod(
            Invocation.getter(#dioClient),
            returnValue: _FakeDioClient_0(this, Invocation.getter(#dioClient)),
          )
          as _i2.DioClient);

  @override
  _i4.Future<String> getUploadUrl(String? submissionId) =>
      (super.noSuchMethod(
            Invocation.method(#getUploadUrl, [submissionId]),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getUploadUrl, [submissionId]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> uploadTransfert({
    required String? url,
    required Map<String, dynamic>? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadTransfert, [], {
              #url: url,
              #payload: payload,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> ping() =>
      (super.noSuchMethod(
            Invocation.method(#ping, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void logFormData(_i8.FormData? formData) => super.noSuchMethod(
    Invocation.method(#logFormData, [formData]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i9.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Stream<bool> get onConnectivityChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onConnectivityChanged),
            returnValue: _i4.Stream<bool>.empty(),
          )
          as _i4.Stream<bool>);
}

/// A class which mocks [UssdTransport].
///
/// See the documentation for Mockito's code generation for more information.
class MockUssdTransport extends _i1.Mock implements _i10.UssdTransport {
  MockUssdTransport() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> sendPart(String? encodedPart) =>
      (super.noSuchMethod(
            Invocation.method(#sendPart, [encodedPart]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
